website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func
from datetime import datetime

class Friend(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    friend_type = db.Column(db.String(50))
    years = db.Column(db.Integer)
    common = db.Column(db.Text)
    likes = db.Column(db.Text)
    how_met = db.Column(db.Text)
    best_memory = db.Column(db.Text)
    additional_info = db.Column(db.Text)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Friend('{self.name}', '{self.friend_type}')"

    @property
    def user(self):
        return User.query.get(self.user_id)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    friends = db.relationship('Friend', backref='owner', lazy=True)

    def __repr__(self):
        return f"User('{self.email}', '{self.first_name}')"



website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Friend
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from .import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in succesfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password.', category='error')
        else:
            flash('Email does not exist', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('Name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords dont match.', category='error')
        elif len(password1) < 7:
            flash('Password must be greater than 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created.', category='success')
            return redirect(url_for('views.home'))


    return render_template("sign_up.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from . import db
from .models import Friend

views = Blueprint('views', __name__)

@views.route('/')
def index():
    return render_template('index.html')

@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)

@views.route('/friend', methods=['POST', 'GET'])
@login_required
def add_friend():
    if request.method == 'POST':
        name = request.form.get('name')
        friend_type = request.form.get('friend_type')
        description = request.form.get('description')
        likes = request.form.get('likes')
        years = request.form.get('years')
        how_met = request.form.get('how_met')
        best_memory = request.form.get('best_memory')
        additional_info = request.form.get('addnl_info')
        new_friend = Friend(name=name, friend_type=friend_type, description=description, likes=likes, how_met=how_met, best_memory=best_memory, years=years, additional_info=additional_info, owner=current_user)
        db.session.add(new_friend)
        db.session.commit()
        flash('Friend added!', category='success')
        return redirect(url_for('views.home'))

    return render_template("friend.html", user=current_user)

@views.route('/edit_friend/<int:friend_id>', methods=['GET', 'POST'])
@login_required
def edit_friend(friend_id):
    friend = Friend.query.get_or_404(friend_id)
    if request.method == 'POST':
        friend.name = request.form.get('name')
        friend.friend_type = request.form.get('friend_type')
        friend.description = request.form.get('description')
        friend.likes = request.form.get('likes')
        friend.years = request.form.get('years')
        friend.how_met = request.form.get('how_met')
        friend.best_memory = request.form.get('best_memory')
        friend.additional_info = request.form.get('addnl_info')
        db.session.commit()
        flash('Friend updated!', category='success')
        return redirect(url_for('views.home'))

    return render_template("edit_friend.html", user=current_user, friend=friend)

@views.route('/delete_friend/<int:friend_id>', methods=['POST'])
@login_required
def delete_friend(friend_id):
    friend = Friend.query.get_or_404(friend_id)
    db.session.delete(friend)
    db.session.commit()
    flash('Friend deleted!', category='success')
    return redirect(url_for('views.home'))

website/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <style>
      body {
        background-color: #bbe4e9;
      }
      .form-control {
        background-color: #e3f6f5;
      }
      .btn {
        background-color: #142d4c;
        border: 0;
      }
      .navbar {
        background-color: #142d4c;
      }
    </style>
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <nav style="color: #bbe4e9;" class="navbar navbar-expand-lg navbar-dark bg-#142d4c">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/home">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages%} {% if category ==
    'error'%}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/";
        });
      }
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script type="text/javascript"
    src="{{ url_for('static', filename='index.js') }}">
    </script>
    {% endblock %}
  </body>
</html>

website/templates/edit_friend.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h2>Edit Friend</h2>
        <form action="{{ url_for('views.edit_friend', friend_id=friend.id) }}" method="post">
            <div class="form-group">
                <label for="name">Name</label>
                <input required type="text" class="form-control" id="name" name="name" value="{{ friend.name }}">
            </div>
            <div class="form-group">
                <label for="friend_type">Type of Friend</label>
                <select class="form-control" id="friend_type" name="friend_type">
                  <option value="">Select a friend type</option>
                  <option value="Home friend">Home friend</option>
                  <option value="Acquaintance">Acquaintance</option>
                  <option value="Relative">Relative</option>
                  <option value="Schoolmate">Schoolmate</option>
                  <option value="Collegemate">Collegemate</option>
                  <option value="Childhood friend">Childhood friend</option>
                  <option value="Other">Other</option>
                </select>
              </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea class="form-control" id="description" name="description">{{ friend.description }}</textarea>
            </div>
            <div class="form-group">
                <label for="likes">Likes</label>
                <textarea class="form-control" id="likes" name="likes">{{ friend.likes }}</textarea>
            </div>
            <div class="form-group">
                <label for="years">Years known</label>
                <input type="text" class="form-control" id="years" name="years" value="{{ friend.years }}">
            </div>
            <div class="form-group">
                <label for="how_met">How we met</label>
                <textarea class="form-control" id="how_met" name="how_met">{{ friend.how_met }}</textarea>
            </div>
            <div class="form-group">
                <label for="best_memory">Best memory</label>
                <textarea class="form-control" id="best_memory" name="best_memory">{{ friend.best_memory }}</textarea>
            </div>
            <div class="form-group">
                <label for="addnl_info">Additional Info</label>
                <textarea class="form-control" id="addnl_info" name="addnl_info">{{ friend.additional_info }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
{% endblock %}

website/templates/friend.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Friend</h2>
  <form method="POST" action="{{ url_for('views.add_friend') }}">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" required>
    </div>
 <div class="form-group">
  <label for="friend_type">Type of Friend</label>
  <select class="form-control" id="friend_type" name="friend_type">
    <option value="">Select a friend type</option>
    <option value="Home friend">Home friend</option>
    <option value="Acquaintance">Acquaintance</option>
    <option value="Relative">Relative</option>
    <option value="Schoolmate">Schoolmate</option>
    <option value="Collegemate">Collegemate</option>
    <option value="Childhood friend">Childhood friend</option>
    <option value="Other">Other</option>
  </select>
</div>

    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" id="description" name="description" rows="3"></textarea>
    </div>
    <div class="form-group">
      <label for="likes">Likes</label>
      <textarea class="form-control" id="likes" name="likes" rows="3"></textarea>
    </div>
    <div class="form-group">
      <label for="years">Years known</label>
      <input type="number" class="form-control" id="years" name="years">
    </div>
    <div class="form-group">
      <label for="how_met">How we met</label>
      <textarea class="form-control" id="how_met" name="how_met" rows="3"></textarea>
    </div>
    <div class="form-group">
      <label for="best_memory">Best memory</label>
      <textarea class="form-control" id="best_memory" name="best_memory" rows="3"></textarea>
    </div>
    <div class="form-group">
      <label for="addnl_info">Additional Info</label>
      <textarea class="form-control" id="addnl_info" name="addnl_info" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Add Friend</button>
  </form>

  <hr>

 
{% endblock %}

website/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1 class="text-center">Welcome, {{ user.first_name }}</h1>

{% if user.friends %}
<h2 style="margin-top: 25px;" class="text-center">Your friends:</h2>
<ul>
  {% for friend in user.friends %}
  <li>
    <a
      href="#"
      data-toggle="modal"
      data-target="#friend-modal-{{ friend.id }}"
      class="fs-5"
      style="font-size: 23px;"
      >{{ friend.name }}</a
    >
  </li>
  <div
    class="modal fade"
    id="friend-modal-{{ friend.id }}"
    tabindex="-1"
    aria-labelledby="friend-modal-{{ friend.id }}-label"
    aria-hidden="true"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h2
            class="modal-title text-center"
            id="friend-modal-{{ friend.id }}-label"
          >
            {{ friend.name }}
          </h2>
        </div>
        <div class="modal-body">
          {% if friend.friend_type %}
          <h5>Friend Type:</h5>
          <p>{{ friend.friend_type }}</p>
          {% endif %} {% if friend.description %}
          <h5>Description:</h5>
          <p>{{ friend.description }}</p>
          {% endif %} {% if friend.years %}
          <h5>Years Known:</h5>
          <p>{{ friend.years }}</p>
          {% endif %} {% if friend.common %}
          <h5>Common Interests:</h5>
          <p>{{ friend.common }}</p>
          {% endif %} {% if friend.likes %}
          <h5>Likes:</h5>
          <p>{{ friend.likes }}</p>
          {% endif %} {% if friend.how_met %}
          <h5>How You Met:</h5>
          <p>{{ friend.how_met }}</p>
          {% endif %} {% if friend.best_memory %}
          <h5>Best Memory:</h5>
          <p>{{ friend.best_memory }}</p>
          {% endif %} {% if friend.additional_info %}
          <h5>Additional Info:</h5>
          <p>{{ friend.additional_info }}</p>
          {% endif %}
        </div>
        <div class="modal-footer">
          <a
            href="{{ url_for('views.edit_friend', friend_id=friend.id) }}"
            class="btn btn-primary"
            >Edit</a
          >
          <form
            action="{{ url_for('views.delete_friend', friend_id=friend.id) }}"
            method="POST"
          >
            <input type="hidden" name="_method" value="DELETE" />
            <button
              type="submit"
              class="btn btn-danger"
              onclick="return confirm('Are you sure you want to delete this friend?')"
            >
              Delete
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</ul>
{% else %}
<p class="text-center">You haven't added any friends yet.</p>
{% endif %}

<div class="text-center">
  <a href="{{ url_for('views.add_friend') }}" class="btn btn-primary"
    >Add Friend</a
  >
</div>
{% endblock %}

website/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewreport" content="width=device-width, initial-scale=1.0">
	<title>
		PreciousPals
	</title>
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="/static/index.css" />
</head>
<body>
	<div class="container-fluid banner">
		<div class="row">
			<div class="col-md-8 offset-md-2 info">
				<h1 class="text-center">PreciousPals</h1>
				<p class="text-start">
					Welcome to PreciousPals, the online destination for connecting with the people who matter most. In our fast-paced world, it's easy to lose touch with friends and loved ones. But at PreciousPals, we believe in the power of personal connections and the importance of staying connected to those who have played a meaningful role in our lives.
					With PreciousPals, you can store information about your most precious people and the things you have in common, from shared interests and hobbies to cherished memories of the old days. Whether you're looking to reconnect with old friends or strengthen existing relationships, our platform makes it easy to stay in touch and keep those personal connections alive.
					Our mission at PreciousPals is simple: to help you build and maintain meaningful relationships that enrich your life. We understand that life gets busy and it can be challenging to find time to stay connected, but we believe that personal connections are worth the effort. That's why we've created a platform that makes it easy to store important information about your friends and loved ones, so you can easily reach out and stay in touch whenever you want.
					So why not join the PreciousPals community today and start building deeper, more meaningful connections with the people who matter most? Whether you're looking to reconnect with old friends or simply store memories of cherished moments, our platform is the perfect place to start. We look forward to helping you stay connected and build lasting relationships that will stand the test of time.
				
				</p>
				<div style="text-align: center;" class="d-grid gap-2 d-md-block">
					<a href="/login"><button style="background-color: #142d4c; border:#142d4c" class="btn btn-primary" type="button">Log In</button></a>
					<a href="/sign-up"><button style="background-color: #142d4c; border:#142d4c" class="btn btn-primary" type="button">Sign Up</button></a>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

website/templates/login.html
{% extends "base.html" %}
{% block title %}Log In{% endblock %}
{% block content %}
<form method="POST">
    <h3 style="color: #142d4c;" align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <div class="text-center">
      <button type="submit" class="btn btn-primary">Login</button>
    </div>
  </form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
    <h3 style="text-align:center; color: #142d4c;">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="name">Name</label>
    <input
      type="text"
      class="form-control"
      id="name"
      name="name"
      placeholder="Enter Name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <div class="text-center">
    <button type="submit" class="btn btn-primary mx-auto">Sign Up</button>
  </div>
</form>
{% endblock %}